### ISSUE TITLE
uninitialized constant Peddler::Client::ErrorParser

### ISSUE THREAD

**Issue by dbwinger** [hakanensari/peddler#41]
```
from /home/daryl/.rvm/gems/ruby-2.2.2@drewp_tracker/gems/peddler-0.17.0/lib/peddler/client.rb:214:in `decorate_error'
	from /home/daryl/.rvm/gems/ruby-2.2.2@drewp_tracker/gems/peddler-0.17.0/lib/peddler/client.rb:208:in `handle_error'
	from /home/daryl/.rvm/gems/ruby-2.2.2@drewp_tracker/gems/peddler-0.17.0/lib/peddler/client.rb:177:in `rescue in run'
	from /home/daryl/.rvm/gems/ruby-2.2.2@drewp_tracker/gems/peddler-0.17.0/lib/peddler/client.rb:171:in `run'
	from /home/daryl/.rvm/gems/ruby-2.2.2@drewp_tracker/gems/peddler-0.17.0/lib/mws/products/client.rb:26:in `list_matching_products'
```
(Offending line)[https://github.com/hakanensari/peddler/blob/master/lib/peddler/client.rb#L214]

I think you just need a 
``` ruby
require 'peddler/error_parser'
```
in `client.rb`, right?

**Comment by hakanensari** [comment]
Thanks, @dbwinger

**Comment by dbwinger** [comment]
Thank YOU!  That was quick. :)
